### ISSUE TITLE
separate language file

### ISSUE THREAD

**Issue by ericsboro** [Pittini/iobroker-heatingcontrol-vis#17]
Hi,

Your project is really amazing! Would it be anyhow possible to add separate language file with switch somewhere in setting? I'm from Ukraine and translating all important tags manually after every release :) 

If you like the idea — I'm ready to do translation DE-EN-UA and in future can help to maintain it :)

**Comment by Pittini** [comment]
Hi, thanks for the interest. Its not so easy at it sounds, because a lot of Textdata also comes from the Adapter itself. So, i think its necesarry to involve also the HeatingControl Programmer @rg-engineering . If he sees a possibility to integratet different languages, then we can think about how.

**Comment by rg-engineering** [comment]
@ericsboro you closed that issue while I started on adapter side. Do you still need that translation?

**Comment by ericsboro** [comment]
> @ericsboro you closed that issue while I started on adapter side. Do you still need that translation?

I thought you are not really interested in major adapter update, so I closed issue. But translation at least to english would really nice to have :) 
If there’s anything I can do to help - I will be glad to participate :)

**Comment by rg-engineering** [comment]
I'll implement it in adapter first. then we need to find a solution for widgets here...

**Comment by ericsboro** [comment]
Cool! Thanks a ton your your efforts :)

**Comment by rg-engineering** [comment]
see my comment under https://github.com/rg-engineering/ioBroker.heatingcontrol/issues/225 about new Datapoints

**Comment by rg-engineering** [comment]
I used my translations in vis. (not finished everywhere, but almost)
I pushed 3.1.3 version here: https://github.com/rg-engineering/iobroker-heatingcontrol-vis
you also need 2.3.1 from adapter (available here https://github.com/rg-engineering/ioBroker.heatingcontrol)

@ericsboro if you like you can help to verify translations.

**Comment by ericsboro** [comment]
guys, you are awesome :)

here's what i found not translated (with proposed translation to EN):

headers: Allgemeines (General), Uhrzeit (Clock), Wozi (Livingroom), Küche (Kitchen), Raumstatus (Room Status)
subtitles: Profil 1 (Profile 1)
in section "Times/week" -> Mo. to So. (Mo. to Su.)
in separate room info:
<img width="981" alt="Screenshot 2021-03-30 at 11 49 21" src="https://user-images.githubusercontent.com/4315411/112961406-01497500-914e-11eb-9bec-b53213e060c5.png">

**Comment by Pittini** [comment]
Most of still not translated texts are my part, but sorry, im very busy atm, ill do it if i found some time.

**Comment by ericsboro** [comment]
@Pittini can i help with that?

**Comment by rg-engineering** [comment]
I'll continue here...
I would not translate the room-dependent names, as these views have to be configured by the user himself (own data points, etc.) Here we add only templates which could be used by user, but in any case he needs to configure it to his own needs. 

BTW @ericsboro : You can find all translations here:
https://github.com/rg-engineering/ioBroker.heatingcontrol/blob/master/lib/vis_words.js
If you like you can change it there and create PullRequest

**Comment by Pittini** [comment]
Working on it now. Found the following Issues:
1. heatingcontrol.0.vis.translations.cardHzngMoFrSaSu.SaSu has Text: Sa. bis Su. - should be Sa. bis So.
2. Missing translation for Infomsg Text: "Steuerelemente ausgeblendet, keine Absenkmethode gewählt."  at heatingcontrol.0.vis.translations.cardHzngProfilParam
3. Missing Translation for caption "Profilparam." at heatingcontrol.0.vis.translations.cardHzngProfilParam
4. Missing Translation for caption "Allgemeines" at heatingcontrol.0.vis.translations.cardHzngGlobals
5. Missing Translation for caption Raumstatus for cardHzngRooms
6. Missing Translation for Navbar Text "Aktives Profil" and "Raum" for abar

**Comment by rg-engineering** [comment]
see my comments:

- heatingcontrol.0.vis.translations.cardHzngMoFrSaSu.SaSu has Text: Sa. bis Su. - should be Sa. bis So.
-> will be available with next commit

- Missing translation for Infomsg Text: "Steuerelemente ausgeblendet, keine Absenkmethode gewählt." at heatingcontrol.0.vis.translations.cardHzngProfilParam
->  you'll find it under heatingcontrol.0.vis.translations.cardHzngProfilParam.HintNotEnabled

- Missing Translation for caption "Profilparam." at heatingcontrol.0.vis.translations.cardHzngProfilParam
-> will be available with next commit

- Missing Translation for caption "Allgemeines" at heatingcontrol.0.vis.translations.cardHzngGlobals
-> you'll find it under heatingcontrol.0.vis.translations.cardHzngGlobals.General

- Missing Translation for caption Raumstatus for cardHzngRooms
-> you'll find it under heatingcontrol.0.vis.translations.cardHzngRooms.RoomState

- Missing Translation for Navbar Text "Aktives Profil" and "Raum" for abar
-> you'll find it under  heatingcontrol.0.vis.translations.tnav.ActiveProfile and heatingcontrol.0.vis.translations.tnav.Room

**Comment by Pittini** [comment]
Its done. Added copy Buttons also. [See V-3.2.0](https://github.com/Pittini/iobroker-heatingcontrol-vis/blob/master/V3.2.0-Vis-HeatingControl.zip)

**Comment by Pittini** [comment]
@ericsboro Und wer übersetzt jetzt die readme/Installationsanweisung auf russisch? :)

**Comment by ericsboro** [comment]
@Pittini i can check translation EN-RU.
